[package]
name = "termCA"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
rand = "0.8.5"
ratatui = "0.28.1"
tui-big-text = "0.6.0"
tui-input = "0.10.1"
tui-scrollview = "0.4.0"
